// <auto-generated />
namespace OAuth.Provider.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Accesstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Accesstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201505250655362_Accesstable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
